name: bid_for_cars
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # annotations
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # api utils
  dio: ^5.2.1
  dart_jsonwebtoken: ^2.8.0

  # caching
  flutter_secure_storage: ^8.0.0

  # dependency_injection
  injectable: ^2.1.1

  # fonts
  google_fonts: ^4.0.5

  # functional
  dartz: ^0.10.1

  # icons
  cupertino_icons: ^1.0.2

  # i18n
  flutter_localizations:
    sdk: flutter
  slang: ^3.17.0
  slang_flutter: ^3.17.0

  # routing
  auto_route: ^6.3.0

  # state management
  flutter_bloc: ^8.1.3

  # utils
  flutter_svg: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  jwt_decoder: ^2.0.1
  validators: ^3.0.0

  # ui plugins
  dots_indicator: ^3.0.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  # code analyzers
  flutter_lints: ^2.0.1

  # code generation
  freezed: ^2.3.2

  # generators
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1

  # mocking
  http_mock_adapter: ^0.4.4

  # testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.3
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/illustrations/
    - assets/svgs/icons/home/navi_bar/
    - assets/svgs/icons/home/car_card/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
