on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - staging

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter packages pub run build_runner clean
      - run: flutter packages pub run build_runner build -d
      - run: flutter pub run slang
#      - run: flutter test
      - run: flutter build apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/ios/iphoneos/app.ipa"
          tag: v0.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}


# push to main
# pull request on main