name: "Build & Release"

on:
  push:
    branches: [ 'main','staging' ]

  # for manual run
  workflow_dispatch:

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
          cache: true
      - run: flutter pub get
      - run: flutter packages pub run build_runner clean
      - run: flutter packages pub run build_runner build -d
      - run: flutter pub run slang
      #      - run: flutter test

      # Get version from pubspec.yaml
      - name: Get version
        id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.version' 'pubspec.yaml'

      - name: Print version
        run: echo ${{ steps.yq.outputs.result }}

      - run: flutter build apk

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/ios/iphoneos/app.ipa"
          tag: ${{ steps.yq.outputs.result }} #v0.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}


# push to main
# pull request on main